name: Deploy to heroku.
​
on:
  push:
    branches: [master]
​
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
​
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1

      - name: Set Env Vars
        uses: microsoft/variable-substitution@v1 
        with:
          files: './keeprserver/appsettings.json'
        env:
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
​
      - name: dotnet publish
        run: |
          dotnet publish ./SERVERFOLDERNAME -c Release 
​
      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
​
          email: ${{ secrets.HEROKU_EMAIL }}

          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
​
          dockerfile_directory: ./keeprserver
​
